# Generated by Django 5.0.6 on 2024-06-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenbed',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gms_app.garden'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='garden_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gms_app.gardenbed'),
        ),
    ]
