# Generated by Django 5.0.6 on 2024-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0002_alter_gardenbed_garden_alter_plant_garden_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='garden_bed',
        ),
        migrations.AddField(
            model_name='plant',
            name='garden_bed',
            field=models.ManyToManyField(blank=True, null=True, to='gms_app.gardenbed'),
        ),
    ]
