# Generated by Django 5.0.6 on 2024-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0003_remove_plant_garden_bed_plant_garden_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='garden_bed',
            field=models.ManyToManyField(blank=True, to='gms_app.gardenbed'),
        ),
    ]
