# Generated by Django 5.0.6 on 2024-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0004_alter_plant_garden_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
