# Generated by Django 5.0.6 on 2024-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0005_plant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenbed',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
