# Generated by Django 5.0.6 on 2024-06-05 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0006_gardenbed_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garden',
            options={'ordering': ['name'], 'verbose_name': 'Garden', 'verbose_name_plural': 'Gardens'},
        ),
        migrations.AlterModelOptions(
            name='gardenbed',
            options={'ordering': ['name'], 'verbose_name': 'Garden Bed', 'verbose_name_plural': 'Garden Beds'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.RemoveField(
            model_name='gardenbed',
            name='location',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='garden_bed',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='location',
        ),
        migrations.AlterField(
            model_name='garden',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the garden'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(help_text='Enter the name of the garden', max_length=50, verbose_name='Garden Name'),
        ),
        migrations.AlterField(
            model_name='gardenbed',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the garden bed'),
        ),
        migrations.AlterField(
            model_name='gardenbed',
            name='garden',
            field=models.ForeignKey(blank=True, help_text='Select the garden this bed belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='gms_app.garden'),
        ),
        migrations.AlterField(
            model_name='gardenbed',
            name='name',
            field=models.CharField(help_text='Enter the name of the garden bed', max_length=100, verbose_name='Bed Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Enter the name of the plant', max_length=50, unique=True, verbose_name='Plant Name'),
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(default=dict, help_text='Enter the location of the plant in the garden bed as a JSON object')),
                ('garden_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='gms_app.gardenbed')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='gms_app.plant')),
            ],
            options={
                'verbose_name': 'Planting',
                'verbose_name_plural': 'Plantings',
                'unique_together': {('plant', 'garden_bed', 'location')},
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='garden_beds',
            field=models.ManyToManyField(blank=True, help_text='Select the garden beds where this plant is located', related_name='plants', through='gms_app.Planting', to='gms_app.gardenbed'),
        ),
    ]
