# Generated by Django 5.0.6 on 2024-06-05 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0007_add_planting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantpreset',
            options={'ordering': ['name'], 'verbose_name': 'Planting', 'verbose_name_plural': 'Plantings'},
        ),
    ]
