# Generated by Django 5.0.6 on 2024-06-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0008_alter_plantpreset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantpreset',
            options={'ordering': ['name'], 'verbose_name': 'Plant preset', 'verbose_name_plural': 'Plant presets'},
        ),
        migrations.AlterUniqueTogether(
            name='planting',
            unique_together={('garden_bed', 'location')},
        ),
    ]
