# Generated by Django 5.0.6 on 2024-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0009_alter_plantpreset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='planting_date',
            field=models.DateField(blank=True, help_text='Enter the date of the planting', null=True, verbose_name='Planting date'),
        ),
    ]
