# Generated by Django 5.0.6 on 2024-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms_app', '0010_planting_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenbed',
            name='location',
            field=models.JSONField(default=dict, help_text='Enter the location of the garden bed in garden as a JSON object'),
        ),
    ]
