# Generated by Django 5.0.6 on 2024-07-09 18:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gms_app', '0011_gardenbed_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter note category name', max_length=32, unique=True, verbose_name='Note category name')),
                ('acronym', models.CharField(help_text='Enter note category acronym', max_length=5, unique=True, verbose_name='Acronym')),
                ('description', models.CharField(blank=True, help_text='Enter note category description', max_length=127, unique=True, verbose_name='Note category description')),
            ],
            options={
                'verbose_name': 'Note Category',
                'verbose_name_plural': 'Note Categories',
                'ordering': ['acronym'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Input key (id) of the data in foreign_table')),
                ('title', models.CharField(help_text='Enter note title', max_length=32, verbose_name='Note title')),
                ('text', models.TextField(blank=True, help_text='Enter note text')),
                ('date', models.DateTimeField(default=datetime.datetime.now, help_text='Enter the date of the note', null=True, verbose_name='Date of the note')),
                ('content_type', models.ForeignKey(help_text='Select on which model to place note', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('category', models.ManyToManyField(blank=True, help_text='Select note category', related_name='notes', to='gms_app.notecategory')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['date'],
            },
        ),
    ]
