name: tests
on: [ pull_request, workflow_dispatch ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r dev_requirements.txt

      - name: Test with pytest
        # working-directory: ./app
        run: pytest --html=report.html --self-contained-html -vv --log-cli-level INFO

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            report.html
#            test_log.log

          retention-days: 5
